name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
      - name: react-native-build-ios
   # You may pin to the exact commit or the version.
  # uses: AustinMcGuinn/react-native-build-ios@0759f8cfa5d457c6b476e04bda50da4670a219dc
        uses: AustinMcGuinn/react-native-build-ios@v1.0.0
